name: Auto-Green

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # 每15分钟执行一次

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config --local user.name "Ymgjdsh"
          git config --local user.email "Ymgjdsh@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
