name: Auto-Green

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # 周一到周六 UTC 0 点执行，也就是北京时间早上 8 点

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --local user.name "HDXXUS"
          git config --local user.email "HDXXUS@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
